### ISSUE TITLE
Error ved forkert input

### ISSUE THREAD

**Issue by KneeCapStealer** [J0pper/stenSaksPapir#1]
### Lowercase Input
Når du får brugerens input kan brugeren skrive hvad som helst. Dette er fint, men du glemmer at tjekke om inputtet er korrekt, og det kan crashe programmet hvis det ikke gøres bedre.
Derfor kunne du skrive:
```py
brugersvar = input(skriv dit valg her).lower()
```
Dette gør så uanset hvad er dit svar i lowercase så jeg kunne skrive: `StEn` og det ville stadigt virke.

### Check Inputtet
Nu mangler du bare at checke om ordet er korrekt, f.eks. er det muligt at skrive `shotgun` og programmet ville crash.
dette kan gøres super simpelt ved at skrive:
```py
if brugersvar in mugligesvar:
  #gå videre
else:
  #skriv en error og tag input igen

```

#### Edits:
1. tilføjede paranteser ved .lower function

**Comment by J0pper** [comment]
Øhøh jeps så dette hjalp mega meget. Nu kan man ikke være en dum bruger og skrive dumme ting længere!.
TAK :D
