### ISSUE TITLE
Gør din kode lidt frækkere

### ISSUE THREAD

**Issue by KneeCapStealer** [J0pper/stenSaksPapir#2]
## Bedre Win Check
Så dette er ikke nødvendigt, men du kunne optimiserer koden lidt.
Dette tager udgangspunkt i at du gerne vil bruge computerens svar som en string. Her vil jeg også forslå at du skriver det ned, måske efter et kort delay med noget suspence, så spillet bliver mere spændene.

#### Her kommer mit forslag:
Du kunne tage indexen af computerens svar og compare det med brugerens. Dette kan gøres med `.index(søg noget i listen her)`
Så kan du tjekke om indexen af computerens svar er lavere end brugerens. Hvis den er det så taber man, med mindre brugeren er på index 0, så skal man tjekke om computeren er på index 3.

På den måde kan man tjekke om man vinder med meget kortere kode (du skal stadig tjekke svarende er det samme)

Hvis du har spørgesmpl så prøv at kommenter, gad godt se en kommentar xD

**Comment by J0pper** [comment]
Din forslag med at tage bruge af index er blevet implementeret og det virker perfekt! Der er nu også noget dejlig suspense O_O.
Tak :D

**Comment by Robotto** [comment]
Jeg er enig i at der er noget interessant i at bruge listeindex til at tjekke lighed mellem to svar, men jeg tænker at det påvirker kodens læsbarhed negativt at man skal op i listen og se hvad de indexes repræsenterer for at forstå logikken i de if sætninger som  finder vinderen... Der er helt sikkert mange elegante måder at gøre det på, men denne løsning gør det svært at forstå koden.

**Comment by KneeCapStealer** [comment]
> Jeg er enig i at der er noget interessant i at bruge listeindex til at tjekke lighed mellem to svar, men jeg tænker at det påvirker kodens læsbarhed negativt at man skal op i listen og se hvad de indexes repræsenterer for at forstå logikken i de if sætninger som finder vinderen... Der er helt sikkert mange elegante måder at gøre det på, men denne løsning gør det svært at forstå koden.

Tænkte godt på det efter jeg havde set det programmeret. Oh well ¯\\_(ツ)_/¯
